name: Check PR Title
description: Validates the PR title format and extracts ISSUE_KEY.

inputs:
  pr_title:
    description: The title of the Pull Request.
    required: true

outputs:
  issue_key:
    description: Extracted ISSUE_KEY from the PR title.

runs:
  using: "composite"
  steps:
    - name: Validate PR Title Format
      id: validate_title  # Устанавливаем id для шага, чтобы использовать его выходные данные
      shell: bash
      run: |
        echo "📌 Validating PR title: ${{ inputs.pr_title }}"

        # Проверяем формат и извлекаем ключ задачи
        if [[ "${{ inputs.pr_title }}" =~ ^(REWIND-[1-9][0-9]*): ]]; then
          ISSUE_KEY="${BASH_REMATCH[1]}"
          echo "🔑 Extracted ISSUE_KEY: $ISSUE_KEY"
          
          # Передаем значение ISSUE_KEY как output
          echo "::set-output name=issue_key::$ISSUE_KEY"
        else
          echo "❌ Invalid PR title format. Expected 'REWIND-{number}: description'"
          exit 1
        fi
