name: Update Task Status on In Review

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title Format
        id: check_pr_title
        uses: ./.github/actions/check-pr-title  # Используем экшн для проверки названия PR
        with:
          pr_title: ${{ github.event.pull_request.title }}

      - name: Update Task Status to "In Review"
        uses: ./.github/actions/update-task-status  # Используем экшн для обновления статуса
        with:
          issue_key: ${{ steps.check_pr_title.outputs.issue_key }}  # Передаём ключ задачи из предыдущего экшна
          transition_id: "inReview1"
          yandex_token: ${{ secrets.YANDEX_TRACKER_TOKEN }}
          yandex_org_id: ${{ secrets.YANDEX_CLOUD_ORG_ID }}
